# Runs all the Python SDK tests within the `tests/` directory to check our code

name: CI Tests
permissions: read-all

on:
  # trunk-ignore(yamllint/empty-values)
  workflow_dispatch:

  push:
    branches:
      - main
      - develop
      - trunk-merge/**
  pull_request:
    branches:
      - main
      - develop
      - "*"

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: pip install local package
        run: python -m pip install .

      - name: pip install requirements_dev.txt
        run: python -m pip install -r requirements_dev.txt

      - name: Run pytest on tests/
        run: python -m pytest ./tests/
