# use pytest-cov to see what percentage of the code is being covered by tests
# WARNING: this workflow will fail if any of the tests within it fail

name: Test Coverage
permissions: read-all

on:
  push:
    branches:
      - main
      - develop
      - trunk-merge/**
  pull_request:
    branches:
      - main
      - develop

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: upgrade pip
        run: pip install --upgrade pip

      - name: Install Pral
        run: pip install -e .

      - name: Install requirements_dev.txt
        run: pip install -r requirements_dev.txt

      - name: Test Coverage
        run: pytest --cov --cov-fail-under=90
